### ISSUE TITLE
Unmatched '[' error

### ISSUE THREAD

**Issue by octaviospain** [docopt/docopt.java#9]
Hi, I just discovered docopt and is awesome! Im using it with some of my applications but i'm getting a `org.docopt.DocoptLanguageError: unmatched '['`error with this _DOC_ `String` 

``` java
private static final String DOC = "Random File Copier.\n\n"+
                                      "Usage:\n"+
                                      "  RandomFileCopier <source_directory> <target_directory> <max_files> [--hidden] [--folders]\n\n"+
                                      "Options:\n"+
                                      "  <max_files>\tThe maximum number of files.\n"+
                                      "  --hidden\tInclude hidden files.\n"+
                                      "  --folders\tInclude folders.\n\n";
```

I realized that the options `[--hidden] [--folders]`are causing this, either placing it in the same usage line or in a new one above. I get the same error trying with required options with parenthesis `()` both in the usage section and in the options section. I readed carefully the instructions provided in the `README`and in the given example but i can't fix this. Thanks in advance.

**Comment by damiengiese** [comment]
Hi, Otto. You've got one small error in your Options section, very easy to miss! The options _must_ be separated from their informal descriptions by at least _two spaces_. You've used tabs, which is confusing the parser. Hope this helps.
